development:
  adapter: mysql
  host: localhost
  username: user_name
  database: dev_db_name
  encoding: utf8

test:
  adapter: mysql
  host: localhost
  username: user_name
  database: test_db_name
  encoding: utf8

production:
  adapter: mysql
  host: localhost
  username: user_name
  database: db_name
  encoding: utf8

